# Database Configuration
#spring.datasource.url=jdbc:sqlserver://nir.database.windows.net:1433;databaseName=test;encrypt=false
#spring.datasource.username=su@nir
#spring.datasource.password=User1234
#${prod_PASSWORD}
